### ISSUE TITLE
link for contribution guidelines

### ISSUE THREAD

**Issue by playmobilmeister** [ecoevo-social/docs.ecoevo.social#38]
The link in the Repo's home to contribution guidelines leads to a 404 error.

Is [this](https://docs.ecoevo.social/contributing.html) it?

**Comment by alxsimon** [comment]
Thanks, forgot to update that when moving the website

**Comment by playmobilmeister** [comment]
I can help making such corrections, as well as do stuff with Quarto, but it seems that the repo is not open to forking to non-members. If you would like some help with editing docs, I'm sure I can provide some, but I'll probably need some membership. Or you can send me individual files and I can work on them

**Comment by alxsimon** [comment]
I already fixed that, thanks, this was a quick and straightforward change.
As for fixing stuff, you're welcome to do pull-requests (here is the [github documentation on that](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)).

**Comment by playmobilmeister** [comment]
Ok, the issue was that I was viewing GitHub on its mobile website version. Im the desktop version I cam fork
